### ISSUE TITLE
`nrf-recover` step won't be required ...

### ISSUE THREAD

**Issue by japaric** [ferrous-systems/embedded-trainings-2020#108]
... after https://github.com/knurling-rs/probe-run/pull/108 makes its way into a crates.io release of `probe-run` AND
the version of `cargo-flash` and `cargo-embed` we recommend to install are both using probe-rs v0.10 (that'd be cargo-flash 0.10.1 and cargo-embed 0.10.0)

**Comment by japaric** [comment]
this `nrf-recover` step: https://embedded-trainings.ferrous-systems.com/installation.html#nrf-recover

(source code: https://github.com/ferrous-systems/embedded-trainings-2020/blob/e78140f8ac54d0c5d38d87af60a0ae78692e292b/embedded-workshop-book/src/installation.md#nrf-recover)

**Comment by Lotterleben** [comment]
closed with https://github.com/ferrous-systems/embedded-trainings-2020/pull/118
