### ISSUE TITLE
use defmt logging

### ISSUE THREAD

**Issue by Lotterleben** [ferrous-systems/embedded-trainings-2020#111]
Quote @japaric from internal chat:

>  right now the workshop uses the log crate + core::fmt (uncompressed, uncolored logs).
> because the workshop also demoes cargo-embed and cargo-flash (which don't support defmt) the board support crate in the workshop material needs to support both log and defmt. I think adding a Cargo feature to the dk board support crate to switch between log and defmt would be the way to go here.

(+1 to that)

**Comment by japaric** [comment]
a blocker here is `char` support in defmt; that type is used in the beginner workshop. Support for `core::time::Duration` would also be nice to have.

defmt 0.1.x doesn't support formatting the `char` type. defmt 0.2.0 will, though.
