### ISSUE TITLE
Python 3.9, macOS and nrfutil

### ISSUE THREAD

**Issue by gsurrel** [ferrous-systems/embedded-trainings-2020#114]
Hi,

I started following the training material, up to the point where to flash the dongle.

This relies on `nrfutil`, and failed. Long story short, it turns out that using `pip install nrfutil` from a Python 3.9 setup (using Homebrew) fetches `nrfutil` 5.2.0, which is targeting Python2. Here is the [corresponding issue in the `pc-nrfutil` repository](https://github.com/NordicSemiconductor/pc-nrfutil/issues/336).

I opened this issue in case someone else also encounter this problem. Maybe you want to update the training material while this situation exists?

Anyway, I like the course up to now, thank you for your work! ❤️

**Comment by japaric** [comment]
thanks for the report. I'm documenting a workaround in the book itself in PR #115
