### ISSUE TITLE
Building an Embedded Program introduces a lot of concepts

### ISSUE THREAD

**Issue by skade** [ferrous-systems/embedded-trainings-2020#24]
https://github.com/ferrous-systems/embedded-trainings-2020/blob/master/beginner-workshop/src/building-programm.md

has a bottom section that introduces "sections" (a term that may be unknown) and a lot of other jargon (ISA, etc.). This should either be more thoroughly explained or sectioned (e.g. by a headline "In detail") off for people that are new to handling binaries - maybe both :).

**Comment by Mirabellensaft** [comment]
I separated the entire binary size chapter and within it, reorganized the information about sections. Please check if you would consider this solved

**Comment by skade** [comment]
Checked https://github.com/ferrous-systems/embedded-trainings-2020/blob/master/embedded-workshop-book/src/binary-size.md and I think it's great.
