### ISSUE TITLE
Radio Puzzle: crate level documentation of heapless is not enough

### ISSUE THREAD

**Issue by skade** [ferrous-systems/embedded-trainings-2020#27]
https://github.com/ferrous-systems/embedded-trainings-2020/blob/master/beginner-workshop/src/radio-puzzle.md links to the heapless toplevel examples.

They do not contain examples on how to create an IndexMap. Navigating to https://docs.rs/heapless/0.5.5/heapless/struct.IndexMap.html provides you with examples to build a `FnvIndexMap`.

Quick examples inline would be useful to avoid frustrating people when constructing their first datastructure.

**Comment by Lotterleben** [comment]
Good point. I'll take care of this now.
