### ISSUE TITLE
Align solution usb-2 and usb-3 template

### ISSUE THREAD

**Issue by skade** [ferrous-systems/embedded-trainings-2020#37]
usb-2-solution differs from usb-3, which is much simpler.

https://github.com/ferrous-systems/embedded-trainings-2020/blob/master/advanced/firmware/src/bin/usb-2-solution.rs#L48-L64

https://github.com/ferrous-systems/embedded-trainings-2020/blob/master/advanced/firmware/src/bin/usb-3.rs#L52-L56

**Comment by Lotterleben** [comment]
Ah, I strumbled across this too and wasn't sure if this is a bug or a feature – @japaric was this intentional?

**Comment by japaric** [comment]
helper methods are a reward for people that read the API docs while working on usb-2. In usb-2-solution we should show that they exist with at least one example (show the two ways to read the L/H registers).

**Comment by Lotterleben** [comment]
@skade is there any other way you would've wanted to be presented with this info?
