### ISSUE TITLE
Both USB-3 and USB-4 require implementation of GET_DESCRIPTOR Configuration

### ISSUE THREAD

**Issue by skade** [ferrous-systems/embedded-trainings-2020#40]
Both USB-3 and USB-4 require implementation of GET_DESCRIPTOR request:

https://github.com/ferrous-systems/embedded-trainings-2020/blame/master/embedded-workshop-book/src/data-stage.md#L11

https://github.com/ferrous-systems/embedded-trainings-2020/blame/master/embedded-workshop-book/src/supporting-standard-requests.md#L5

Only USB-4 needs it.

**Comment by Lotterleben** [comment]
was this resolved by https://github.com/ferrous-systems/embedded-trainings-2020/pull/38?

**Comment by skade** [comment]
@Lotterleben Not quite, I think we can remove the task from USB-3.

**Comment by Lotterleben** [comment]
ah i see. on it.
